// Action Execution Layer v1 — shared structured types.
//
// ROOT CAUSE this module exists to fix: LOIS/IGNIS's chat replies are
// generated by an LLM with NO connection to whether any real backend
// mutation happened. For calendar specifically, nothing even attempted a
// mutation on the path the frontend actually uses (see server.ts's
// /chat/stream route before this change) — the model just narrated a plan.
// For goals/memory, a mutation attempt DID exist but ran fire-and-forget
// AFTER the LLM had already generated and sent its own free-text reply, so
// even a successful mutation's "confirmation" was still just the model's
// own guess, not grounded in a real result — and a rejected/duplicate
// mutation could still be narrated as a success.
//
// This file defines the one shared vocabulary every part of the new
// action-execution pipeline speaks: extraction (actionExtractor.ts) turns
// a message into an AssistantAction; the executor (actionExecutor.ts) turns
// an AssistantAction into a real service call and an ActionResult; the
// server route is the only thing allowed to turn an ActionResult into
// reply text — and it does so by copying the result's own message/error,
// never by asking an LLM to describe what "probably" happened.

export type CalendarRecurrenceFrequency = "daily" | "weekly" | "monthly" | "yearly";

export interface CalendarRecurrence {
  frequency: CalendarRecurrenceFrequency;
  /** e.g. 1 = every year, 2 = every 2 years. Always >= 1. */
  interval: number;
}

// Step 2 — a real discriminated union (not `{ action: string; data: any }`)
// so a switch over `action.type` is exhaustively checked by the compiler
// everywhere an AssistantAction is consumed (see actionExecutor.ts).
export type AssistantAction =
  | {
      type: "calendar.create";
      payload: {
        title: string;
        /** ISO YYYY-MM-DD anchor date. For a recurring event this is the
         *  first/reference occurrence; the year on its own isn't
         *  meaningful beyond that anchor (see calendarRecurrence.ts). */
        date: string;
        timeText?: string;
        recurrence?: CalendarRecurrence;
      };
    }
  | {
      type: "calendar.delete";
      payload: {
        /** Free-text description of which event to delete, resolved
         *  against existing events BY THE EXECUTOR — never a raw id
         *  invented by extraction. Multiple matches -> clarification,
         *  never a guess (Step 21/22). */
        query: string;
      };
    }
  | {
      type: "goal.create";
      payload: {
        /** The original message, handed to the existing
         *  cleanGoalPhrase()/addGoalFromCommand() pipeline verbatim —
         *  reusing that proven parsing rather than re-deriving a title
         *  here. */
        rawMessage: string;
      };
    }
  | {
      type: "goal.complete";
      payload: { query: string };
    }
  | {
      type: "goal.delete";
      payload: { query: string };
    }
  | {
      // Action Execution Layer v2 — a collection-level mutation, distinct
      // from goal.create: "my goals are X, Y, Z" (with an implied "and
      // nothing else") means make the ACTIVE goals collection equal to
      // exactly this list, not add three more goals alongside whatever
      // was already there. See actionExecutor.ts's executeGoalsReplace for
      // the full active-vs-completed semantics (completed goals are never
      // touched by this action — see Objective 3's own report entry).
      type: "goals.replace";
      payload: {
        /** Raw, not-yet-validated titles as extracted from the message —
         *  trimming, dedup, and length/count limits happen in the
         *  executor (validateGoalsReplacePayload), not here, so extraction
         *  stays a pure "what did the user say" step. */
        titles: string[];
      };
    }
  | {
      type: "memory.create";
      payload: {
        /** The original message, handed to the existing explicit-command
         *  pipeline (splitExplicitMemoryCommands/addMemory) verbatim —
         *  same reuse rationale as goal.create above. */
        rawMessage: string;
      };
    };

export type AssistantActionType = AssistantAction["type"];

export interface ActionCandidate {
  id: string;
  label: string;
}

// Which part of application state an action type touches — used for the
// "[chat] <domain> state changed" lifecycle log (Objective 9/19) and for
// telling the frontend/marker payload what changed without either side
// having to hardcode a switch over every individual action type string.
export type ActionDomain = "calendar" | "goals" | "memory";

const ACTION_DOMAINS: Record<AssistantActionType, ActionDomain> = {
  "calendar.create": "calendar",
  "calendar.delete": "calendar",
  "goal.create": "goals",
  "goal.complete": "goals",
  "goal.delete": "goals",
  "goals.replace": "goals",
  "memory.create": "memory",
};

export function actionDomain(type: AssistantActionType): ActionDomain {
  return ACTION_DOMAINS[type];
}

// Step 8 — every execution reports back through this. `success` is the
// primary discriminant; the two failure shapes distinguish a real failure
// (`status: "error"`) from an unresolved ambiguity that must never be
// guessed through (`status: "needs_clarification"`, Step 22).
export type ActionResult =
  | {
      success: true;
      actionType: AssistantActionType;
      /** Grounded, human-readable confirmation — this exact string is what
       *  the assistant is allowed to say. Never regenerated by an LLM. */
      message: string;
      data?: unknown;
    }
  | {
      success: false;
      actionType: AssistantActionType;
      status: "error";
      error: string;
    }
  | {
      success: false;
      actionType: AssistantActionType;
      status: "needs_clarification";
      message: string;
      candidates?: ActionCandidate[];
    };
